---
format:
  revealjs:
    center: true
    slide-number: false
    progress: false
    code-overflow: wrap
    theme: [default, custom.scss]
---

## Discussion: Surveys and Eye-Tracking {.smaller}

<!-- 15-20 minutes -->

- Sirotkina. "Reading Between the Eyes: Recovering (Political) Identity from Eye-Tracking Weak Signal"

- Yang. "Read It or Ignore It? A Personality-Conditioned Computational Model of Gaze Behavior in Political Advertising"

&nbsp;

::: {style="text-align: center"}
**Gustavo Diaz**  
Northwestern University  
<gustavo.diaz@northwestern.edu>  
:::

::: aside
Slides: [talks.gustavodiaz.org/polmeth26](https://talks.gustavodiaz.org/polmeth)
:::


## Why should we care about eye-tracking?

## We do surveys

## We use survey *outcomes*

## We are encouraged to supplement with *behavioral* outcomes

. . .

Why?

## The argument goes


$\text{Attitudes} \rightarrow \text{Behavior}$

We only care about *self-reported* attitudes because they predict *actual* behavior


## The argument goes


$\textbf{Attitudes} \rightarrow \text{Behavior}$

If we only measure **attitudes** we risk bias

## The argument goes


$\textbf{Attitudes} \rightarrow \textbf{Behavior}$

Measuring **behavioral** indicators can reduce/control the bias

## The argument goes


$\textbf{Attitudes} \rightarrow \textbf{Behavior}$

But not easy to incorporate!

## Eye-tracking solution

. . .

$\textbf{Disposition} \rightarrow \text{Attitudes} \rightarrow \text{Behavior}$


. . .

Attention/gaze removes bias from self-reports by avoiding them altogether


## Sirotkina: Recovering identity from eye-tracking

**Importance**

::: incremental
- **Big picture:** Weak signals abound

- Validation of novel methodology

- Eliminates bias from "self-report" gap
:::

## Sirotkina: Recovering identity from eye-tracking

**Pipeline**

1. _**Record**_  [gaze patterns and measure features]{style="color: #FFFFFF00;"}

2. _**Aggregate**_ [across images to recover signal]{style="color: #FFFFFF00;"}

3. _**Classify**_ [via supervised learning with emphasis on regularization]{style="color: #FFFFFF00;"}

[{{< fa arrow-right >}} Apply to surveys with images about immigration, Jan 6, LGBT, guns]{style="color: #FFFFFF00;"}

## Sirotkina: Recovering identity from eye-tracking

**Pipeline**

1. _**Record**_  gaze patterns and measure features
2. _**Aggregate**_ [across images to recover signal]{style="color: #FFFFFF00;"}

3. _**Classify**_ [via supervised learning with emphasis on regularization]{style="color: #FFFFFF00;"}

[{{< fa arrow-right >}} Apply to surveys with images about immigration, Jan 6, LGBT, guns]{style="color: #FFFFFF00;"}

## Sirotkina: Recovering identity from eye-tracking

**Pipeline**

1. _**Record**_  gaze patterns and measure features

2. _**Aggregate**_ across images to recover signal

3. _**Classify**_ [via supervised learning with emphasis on regularization]{style="color: #FFFFFF00;"}

[{{< fa arrow-right >}} Apply to surveys with images about immigration, Jan 6, LGBT, guns]{style="color: #FFFFFF00;"}

## Sirotkina: Recovering identity from eye-tracking

**Pipeline**

1. _**Record**_  gaze patterns and measure features

2. _**Aggregate**_ across images to recover signal


3. _**Classify**_ via supervised learning with emphasis on regularization

[{{< fa arrow-right >}} Apply to surveys with images about immigration, Jan 6, LGBT, guns]{style="color: #FFFFFF00;"}

## Sirotkina: Recovering identity from eye-tracking

**Pipeline**

1. _**Record**_  gaze patterns and measure features

2. _**Aggregate**_ across images to recover signal


3. _**Classify**_ via supervised learning with emphasis on regularization

{{< fa arrow-right >}} Apply to surveys with images about immigration, Jan 6, LGBT, guns

## Sirotkina: Recovering identity from eye-tracking

**Praise**

::: incremental
- Theory of how political identity maps into gaze

- Amazing showcase of methodological expertise!

- Proposing a *pipeline* instead of a *tool*
:::

## Sirotkina: Recovering identity from eye-tracking

**Questions**

::: incremental

- Maybe good that current pipeline is only good at capturing intensity?

- Can we build a "dictionary" of gaze patterns?

- Do we want features to be predictive of *self-reported* identity?

- How does this change downstream inference?

:::

## Yang: Gaze behavior in political advertising

**Importance**

::: incremental
1. Adjusting gaze models to political content
2. Attention depends on who you are and what you believe
:::

## Yang: Gaze behavior in political advertising

**Summary**

- _**Goal:** _ Personality-conditioned model of gaze behavior

- _**Tune:**_ RNNs to learn Big 5 personality weights (Linear Beta Module)

- _**Predict:**_ On held out data (LOGO-CV)


{{< fa arrow-right >}} Apply to student sample ($108 \times 18$)

## Yang: Gaze behavior in political advertising

**Praise**

::: incremental

- Bringing social science focus into eye-tracking

- Differentiable fovea module

- Creative choice of evaluation metrics

:::

## Yang: Gaze behavior in political advertising

**Questions**

::: incremental
- How does workflow scale up?

- Connection with adaptive experimentation?

- What happens if you measure personality differently?

- Beyond **political** **persuasion**?
:::

## Questions

::: {.list-table}

- - Sirotkina
  - Yang
  
- - Capturing intensity only?
  - How does workflow scale up?
  
- - Can we build a dictionary of gaze patterns?
  - Connection with adaptive experimentation?
  
- - Features to be predict *self-reported* identity?
  - Different measures of personality differently?

- - Downstream inference?
  - Beyond political persuasion?

:::


