---
title: "Balancing Precision and Retention in Experimental Design"
subtitle: "Additional Materials"
format: 
  html:
    page-layout: article
navbar: false
toc: true
---

```{r include=FALSE}
library(knitr)

opts_chunk$set(fig.pos = "center", echo = FALSE, 
               message = FALSE, warning = FALSE)
```

```{r setup}
# Packages
library(tidyverse)
library(DeclareDesign)
library(kableExtra)
library(tinytable)


# ggplot global options
theme_set(theme_gray(base_size = 20))

puc_blue = "#0176DE"
```

# Additional information and results

## Sample sizes by experimental condition

```{r}
design_tab = read.csv("list_placebo/design_tab.csv")

colnames(design_tab) = c(
  "X",
  "Sensitive",
  "Placebo",
  "Threaten",
  "Evict",
  "Donation",
  "Work"
)

design_tab[, -1] %>% 
  tt() %>% 
  group_tt(
    j = list(
      "Item location" = 1:2,
      "Sensitive item" = 3:6
    )
  )
```


## Sample characteristics

```{r}
desc_tab = read.csv("list_placebo/descriptive.csv")

desc = desc_tab %>%
  rename(Variable = variable) %>%
  mutate(Variable = case_when(
    Variable == "age" ~ "Age (years)",
    # sex
    Variable == "female" ~ "Female",
    Variable == "male" ~ "Male",
    Variable == "other_sex" ~ "Other sex",
    # education
    Variable == "edu_pri_inc" ~ "Primary incomplete",
    Variable == "edu_pri_com" ~ "Primary complete",
    Variable == "edu_sec_inc" ~ "Secondary incomplete",
    Variable == "edu_sec_com" ~ "Secondary complete",
    Variable == "edu_ter_inc" ~ "Tertiary incomplete",
    Variable == "edu_ter_com" ~ "Tertiary complete",
    # race
    Variable == "white" ~ "White",
    Variable == "afro" ~ "Afro-descendant",
    Variable == "indigenous" ~ "Indigenous",
    Variable == "other_race" ~ "Other race",
    # employment
    Variable == "employed" ~ "Worked last week",
    # income
    Variable == "inc_great_diff" ~ "Not enough, faces great difficulties",
    Variable == "inc_diff" ~ "Not enough, faces some difficulty",
    Variable == "inc_enough" ~ "Enough to make ends meet",
    Variable == "inc_save" ~ "Enough to save",
    .default = NA
  )) %>%
  mutate(Variable = factor(Variable,
                           levels = c(
                             "Age (years)",
                             # sex
                             "Female",
                             "Male",
                             "Other sex",
                             # education
                             "Primary incomplete",
                             "Primary complete",
                             "Secondary incomplete",
                             "Secondary complete",
                             "Tertiary incomplete",
                             "Tertiary complete",
                             # race
                             "White",
                             "Afro-descendant",
                             "Indigenous",
                             "Other race",
                             # employment
                             "Worked last week",
                             # income
                             "Not enough, faces great difficulties",
                             "Not enough, faces some difficulty",
                             "Enough to make ends meet",
                             "Enough to save"
                           ))) %>% 
  select(-X)

desc %>%
  arrange(Variable) %>%
  tt(
    digits = 3
  ) %>% 
  format_tt(j = 3:6, digits = 3, num_fmt = "decimal", num_zero = TRUE) %>% 
  format_tt(markdown = TRUE) %>% 
  group_tt(
    i = list(
      "_Sex_" = 2,
      "_Education_" = 5,
      "_Race_" = 11,
      "_Employment_" = 15,
      "_Income_" = 16
    )
  ) %>% 
  style_tt(i = "~groupi", indent = 1) 

```

## Observed responses

[Convert chi_bar.pdf to png]

## Results with all items

[Convert main.pdf to png]

## Bounds with all items

```{r}
#| fig-width: 8
#| fig-height: 10

bnds = read.csv("list_placebo/bounds.csv")

bd = bnds %>% 
  mutate(Estimator = case_when(
    Estimator == "Single list" &
      list == "count_a" ~ "List A",
    Estimator == "Single list" &
      list == "count_b" ~ "List B",
    Estimator == "DLE" ~ "Pooled",
    .default = Estimator
  )) %>% 
  mutate(boot_ci_which = case_when(
    outcome == "count_hi" & 
      Assumptions == "List" ~ boot_ci_hi,
    outcome == "count_lo" &
      Assumptions == "List" ~ boot_ci_lo,
    .default = boot_ci_which
  )) %>% 
  select(
    Assumptions,
    Estimator, 
    list_treatment,
    outcome,
    estimate,
    boot_ci_which
  ) %>% 
  pivot_wider(
    names_from = outcome,
    values_from = c(estimate, boot_ci_which)
  )


ggplot(bd) +
  aes(x = Assumptions,
      y = estimate_count_hi,
      color = Estimator) +
  geom_hline(yintercept = 0,
             linetype = "dashed") +
  geom_linerange(aes(
    x = rev(Assumptions),
    ymin = estimate_count_lo,
    ymax = estimate_count_hi
  ), linewidth = 3,
  position = position_dodge(width = 0.5)) +
  geom_linerange(aes(
    x = rev(Assumptions),
    ymin = boot_ci_which_count_lo,
    ymax = boot_ci_which_count_hi
  ), linewidth = 1,
  position = position_dodge(width = 0.5)) +
  facet_wrap(~list_treatment, ncol = 1) +
  scale_color_grey(start = 0.8, end = 0) +
  labs(x = "Type of bounds",
       y = "Prevalence") +
  coord_cartesian(ylim = c(-1, 1)) +
  scale_x_discrete(
    labels = c(
      "Sharp", 
      "List experiment\nassumptions"))
```

## Known placebo proportion bounds

```{r}
# bounds_known_prop.csv
bounds_known_prop = read.csv("list_placebo/bounds_known_prop.csv")

# I messed up the proportion labels
bkp_hi = bounds_known_prop %>% 
  mutate(p = case_when(
    p == 1 ~ 0.05,
    p == 2 ~ 0.1,
    p == 3 ~ 0.2,
    p == 4 ~ 0.3
  ),
  estimator = case_when(
    estimator == "List" &
      list == "count_a" ~ "List A",
    estimator == "List" &
      list == "count_b" ~ "List B",
    estimator == "DLE" ~ "Pooled",
    .default = estimator
  )) %>% 
  select(
    p, list_treatment, estimator, 
    estimate_hi = estimate,
    boot_ci_hi,
  )


le = bnds %>% 
  filter(Assumptions == "List") %>% 
  mutate(Estimator = case_when(
    Estimator == "Single list" &
      list == "count_a" ~ "List A",
    Estimator == "Single list" &
      list == "count_b" ~ "List B",
    Estimator == "DLE" ~ "Pooled",
    .default = Estimator
  )) %>% 
# the boot CIs are backwards
  mutate(boot_ci_which = ifelse(
    outcome == "count_hi",
    boot_ci_hi,
    boot_ci_lo
  )) %>% 
    select(
    list_treatment,
    Estimator, 
    outcome,
    estimate,
    boot_ci_which
  ) %>% 
  pivot_wider(
    names_from = outcome,
    values_from = c(estimate, boot_ci_which)
  )

bkp_lo = le %>% select(
  list_treatment,
  estimator = Estimator,
  estimate_lo = estimate_count_lo,
  boot_ci_lo = boot_ci_which_count_lo
)

bkp = left_join(bkp_hi, bkp_lo, by = c("list_treatment", "estimator"))
```

```{r}
#| fig-width: 8
#| fig-height: 10


ggplot(bkp) +
    aes(x = estimator,
      y = estimate_hi,
      color = factor(p)) +
  geom_hline(yintercept = 0,
             linetype = "dashed") +
  geom_linerange(aes(
    x = estimator,
    ymin = estimate_lo,
    ymax = estimate_hi
  ), linewidth = 3,
  position = position_dodge(width = 0.5)) +
  geom_linerange(aes(
    x = estimator,
    ymin = boot_ci_lo,
    ymax = boot_ci_hi
  ),  linewidth = 1,
  position = position_dodge(width = 0.5)) +
  facet_wrap(~list_treatment, ncol = 1) +
  scale_color_grey(start = 0.8, end = 0) +
  labs(
    y = "Prevalence",
    x = "Estimator",
    color = "Proportion\nholding\nplacebo"
  )
  
```

## Bounds with direct questions

[CONTINUE HERE]

# Statistical tests

# Validation study